### ISSUE TITLE
Arrow should be from store_chunks to ARCO bucket

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/flow-charts#4]
In this diagram, the arrow suggest direct flow of data from cache bucket to ARCO bucket. But that's not possible. All data flows through the store_chunks task.
![flow](https://github.com/pangeo-forge/flow-charts/raw/main/renders/xarrayzarr.png)

**Comment by cisaacstern** [comment]
Good point. Layout for this correction is a little dicey, with the options being either crossed lines (as shown below), or totally restructuring the 3-column layout of the diagram. What do you think of:

<img width="556" alt="Screen Shot 2021-09-22 at 6 04 22 PM" src="https://user-images.githubusercontent.com/62192187/134441145-6a81cbca-5398-4844-8d8d-cac15dccf51a.png">
